/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import de.vandermeer.asciitable.AsciiTable
import kotlin.text.toIntOrNull

fun imprimirHeader() {
    println("Bienvenido a almacenes")
    val asciiArt =
            """
         ____ ___ __  __    _    _   _ 
        / ___|_ _|  \/  |  / \  | \ | |
        \___ \| || |\/| | / _ \ |  \| |
         ___) | || |  | |/ ___ \| |\  |
        |____/___|_|  |_/_/   \_\_| \_|
    """.trimIndent()

    println(asciiArt)

    println()
}

fun imprimirInventario(inventario: List<ProductoInventario>) {
    println("Presentamos nuestro catálogo de productos:")

    println()

    val at = AsciiTable()

    // Añadir encabezados de columna
    at.addRule()
    at.addRow("ID - Producto", "Precio", "Cantidad disponible")
    at.addRule()

    // Añadir filas
    inventario.forEach { producto ->
        at.addRow(
                "${producto.producto.id} - ${producto.producto.nombre}",
                "$${producto.producto.precio}",
                "${producto.cantidadDisponible}"
        )
    }

    at.addRule()

    // Imprimir la tabla
    println(at.render())
}

fun main() {

    // Creando inventario

    val inventario = crearInventario()
    val carrito = Carrito()

    imprimirHeader()

    imprimirInventario(inventario)

    print("Escriba el id del producto que quiere añadir al carrito: ")

    var input = readLine() // Leer el input del usuario como String

    val idProducto = input?.toIntOrNull() // Convertir el input a Int de forma segura

    if (idProducto != null) {
        val productoSeleccionado = inventario.find { it.producto.id == idProducto }

        println("")

        if (productoSeleccionado != null) {
            println("Producto seleccionado: ${productoSeleccionado.producto.nombre}")

            print("Ingrese la cantidad: ")

            input = readLine() // Leer el input del usuario como String

            val cantidad = input?.toIntOrNull() // Convertir el input a Int de forma segura

            if (cantidad != null) {
                carrito.agregarProducto(productoSeleccionado.producto, cantidad)

                println("")

                carrito.mostrarCarrito()
            } else {
                println("El valor ingresado en cantidad no es un entero válido.")
            }
        }
    } else {
        println("El valor ingresado no es un número entero válido.")
    }
}
